/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "gbaxrzoyagquqqumnfzk"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdiYXhyem95YWdxdXFxdW1uZnprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQxNzE2MzQsImV4cCI6MjA3OTc0NzYzNH0.bllmSSDBslpuG03gPSv4_-DZLP-oueByvBPoWzDTd24"